//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESkimo.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CssSellector {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CssSellector() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESkimo.Infrastructure.CssSellector", typeof(CssSellector).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.c-table-suppliers__cell.
        /// </summary>
        public static string CrolProductResult_productResult_columns {
            get {
                return ResourceManager.GetString("CrolProductResult_productResult_columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.c-table-suppliers__cell:nth-child(4)&gt;a.c-btn-seller-add-cart.
        /// </summary>
        public static string CrolProductResult_productResult_columns_digiCode {
            get {
                return ResourceManager.GetString("CrolProductResult_productResult_columns_digiCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.c-table-suppliers__cell:nth-child(4)&gt;a.c-btn-seller-add-cart.
        /// </summary>
        public static string CrolProductResult_productResult_columns_digiCodeBuyBox {
            get {
                return ResourceManager.GetString("CrolProductResult_productResult_columns_digiCodeBuyBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.c-table-suppliers__cell:nth-child(2)&gt;p.
        /// </summary>
        public static string CrolProductResult_productResult_columns_digiDepo {
            get {
                return ResourceManager.GetString("CrolProductResult_productResult_columns_digiDepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .c-table-suppliers__seller-info .summary-overlay__info-row .seller-rate .seller-rate__box:nth-child(3) .seller-rate__rating.
        /// </summary>
        public static string CrolProductResult_productResult_columns_noReference {
            get {
                return ResourceManager.GetString("CrolProductResult_productResult_columns_noReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .c-table-suppliers__seller-info .summary-overlay__info-row .seller-rate .seller-rate__box:nth-child(2) .seller-rate__rating.
        /// </summary>
        public static string CrolProductResult_productResult_columns_postingCommitment {
            get {
                return ResourceManager.GetString("CrolProductResult_productResult_columns_postingCommitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.c-table-suppliers__cell:nth-child(4)&gt;.c-price .c-price__value.
        /// </summary>
        public static string CrolProductResult_productResult_columns_price {
            get {
                return ResourceManager.GetString("CrolProductResult_productResult_columns_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .c-table-suppliers__seller-wrapper .c-table-suppliers__rating .c-product__seller-second-line span.u-text-bold.
        /// </summary>
        public static string CrolProductResult_productResult_columns_rate {
            get {
                return ResourceManager.GetString("CrolProductResult_productResult_columns_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .c-table-suppliers__seller-wrapper p.c-table-suppliers__seller-name&gt;span&gt;a.
        /// </summary>
        public static string CrolProductResult_productResult_columns_sellerlink {
            get {
                return ResourceManager.GetString("CrolProductResult_productResult_columns_sellerlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .c-table-suppliers__seller-wrapper p.c-table-suppliers__seller-name&gt;span&gt;a.
        /// </summary>
        public static string CrolProductResult_productResult_columns_sellername {
            get {
                return ResourceManager.GetString("CrolProductResult_productResult_columns_sellername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .c-table-suppliers__seller-info .summary-overlay__info-row .seller-rate .seller-rate__box:nth-child(1) .seller-rate__rating.
        /// </summary>
        public static string CrolProductResult_productResult_columns_timelySupply {
            get {
                return ResourceManager.GetString("CrolProductResult_productResult_columns_timelySupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html body.has-top-banner main#main div#content div.o-page.c-product-page div.container article.c-product.js-product section.c-product__info div.c-product__attributes.js-product-attributes div.c-product__summary.js-product-summary div.c-box div.c-product__seller-info.js-seller-info div.c-product__seller-row.c-product__seller-row--add-to-cart.c-product__add-container.js-add-to-cart-container.js-fast-shopping a.btn-add-to-cart.btn-add-to-cart--full-width.js-add-to-cart.js-product-page-add-to-card.js-btn-add-to [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CrolProductResult_productResult_digiCode {
            get {
                return ResourceManager.GetString("CrolProductResult_productResult_digiCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html body.has-top-banner main#main div#content div.o-page.c-product-page div.container article.c-product.js-product section.c-product__info div.c-product__attributes.js-product-attributes div.c-product__summary.js-product-summary div.c-box div.c-product__seller-info.js-seller-info div.c-product__seller-row.c-product__seller-row--add-to-cart.c-product__add-container.js-add-to-cart-container.js-fast-shopping a.btn-add-to-cart.btn-add-to-cart--full-width.js-add-to-cart.js-product-page-add-to-card.js-btn-add-to [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CrolProductResult_productResult_digiCodeBuyBox {
            get {
                return ResourceManager.GetString("CrolProductResult_productResult_digiCodeBuyBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html body.has-top-banner main#main div#content div.o-page.c-product-page div.container article.c-product.js-product section.c-product__info div.c-product__attributes.js-product-attributes div.c-product__summary.js-product-summary div.c-box div.c-product__seller-info.js-seller-info div.js-seller-info-changable.c-product__seller-box div.c-product__seller-row.js-seller-info-shipment.c-product__seller-row--clickable div.c-product__seller-row-main span.c-product__delivery-warehouse.
        /// </summary>
        public static string CrolProductResult_productResult_digiDepo {
            get {
                return ResourceManager.GetString("CrolProductResult_productResult_digiDepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html body.has-top-banner main#main div#content div.o-page.c-product-page div.container article.c-product.js-product section.c-product__info div.c-product__attributes.js-product-attributes div.c-product__summary.js-product-summary div.c-box div.c-product__seller-info.js-seller-info div.js-seller-info-changable.c-product__seller-box.c-product__seller-box--shadowed div.c-product-info-box__body-wrapper div.c-product-info-box__body div.c-product-info-box__row.js-seller-score-container div.c-product-info-box__fee [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CrolProductResult_productResult_noReference {
            get {
                return ResourceManager.GetString("CrolProductResult_productResult_noReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html body.has-top-banner main#main div#content div.o-page.c-product-page div.container article.c-product.js-product section.c-product__info div.c-product__attributes.js-product-attributes div.c-product__summary.js-product-summary div.c-box div.c-product__seller-info.js-seller-info div.js-seller-info-changable.c-product__seller-box.c-product__seller-box--shadowed div.c-product-info-box__body-wrapper div.c-product-info-box__body div.c-product-info-box__row.js-seller-score-container div.c-product-info-box__fee [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CrolProductResult_productResult_postingCommitment {
            get {
                return ResourceManager.GetString("CrolProductResult_productResult_postingCommitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html body.has-top-banner main#main div#content div.o-page.c-product-page div.container article.c-product.js-product section.c-product__info div.c-product__headline h1.c-product__title.
        /// </summary>
        public static string CrolProductResult_productResult_prductname {
            get {
                return ResourceManager.GetString("CrolProductResult_productResult_prductname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .c-product .c-product__info .c-product__attributes .c-product__summary .c-product__seller-info  .c-product__seller-box .c-product__seller-row.c-product__seller-row--price .c-product__seller-price-real .c-product__seller-price-raw.
        /// </summary>
        public static string CrolProductResult_productResult_Price {
            get {
                return ResourceManager.GetString("CrolProductResult_productResult_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html body.has-top-banner main#main div#content div.o-page.c-product-page div.container article.c-product.js-product section.c-product__info div.c-product__attributes.js-product-attributes div.c-product__summary.js-product-summary div.c-box div.c-product__seller-info.js-seller-info div.js-seller-info-changable.c-product__seller-box.c-product__seller-box--shadowed div.c-product-info-box__body-wrapper div.c-product-info-box__body div.c-product-info-box__row.js-seller-score-container span.u-text-bold.u-text-big [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CrolProductResult_productResult_rate {
            get {
                return ResourceManager.GetString("CrolProductResult_productResult_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .c-product .c-product__info .c-product__attributes .c-product__summary .c-product__seller-info  .c-product__seller-box .c-product-info-box .c-product-info-box__body-wrapper .c-product-info-box__body a.js-seller-name.
        /// </summary>
        public static string CrolProductResult_productResult_sellerlink {
            get {
                return ResourceManager.GetString("CrolProductResult_productResult_sellerlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html body.has-top-banner main#main div#content div.o-page.c-product-page div.container article.c-product.js-product section.c-product__info div.c-product__attributes.js-product-attributes div.c-product__summary.js-product-summary div.c-box div.c-product__seller-info.js-seller-info div.js-seller-info-changable.c-product__seller-box div.c-product__seller-row.c-product__seller-row--seller.c-product__seller-row--clickable.js-seller-info-seller.js-seller-variant div.c-product__seller-row-main div.c-product__sell [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CrolProductResult_productResult_sellername {
            get {
                return ResourceManager.GetString("CrolProductResult_productResult_sellername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #suppliers.c-box-suppliers div.c-box .c-table-suppliers .c-table-suppliers__body .c-table-suppliers__row.
        /// </summary>
        public static string CrolProductResult_productResult_sellers {
            get {
                return ResourceManager.GetString("CrolProductResult_productResult_sellers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html body.has-top-banner main#main div#content div.o-page.c-product-page div.container article.c-product.js-product section.c-product__info div.c-product__attributes.js-product-attributes div.c-product__summary.js-product-summary div.c-box div.c-product__seller-info.js-seller-info div.js-seller-info-changable.c-product__seller-box.c-product__seller-box--shadowed div.c-product-info-box__body-wrapper div.c-product-info-box__body div.c-product-info-box__row.js-seller-score-container div.c-product-info-box__fee [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CrolProductResult_productResult_timelySupply {
            get {
                return ResourceManager.GetString("CrolProductResult_productResult_timelySupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html body.has-top-banner main#main div#content div.container.c-seller div.o-page div.o-page__row div.o-page__aside div.o-page__aside--listing.js-list-aside-container.js-sticky div.c-listing-sidebar.js-sticky-inner div.c-profile-box.c-seller-profile h1.c-profile-box__username.
        /// </summary>
        public static string CrolSellerModel_name {
            get {
                return ResourceManager.GetString("CrolSellerModel_name", resourceCulture);
            }
        }
    }
}
